### ISSUE TITLE
Using nox in precommit

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/python-project-template#20]
What is your opinion about using nox in the precommit hook description ? This would prevent us having redundant configuration of the tools such as `isort --black` and it could just call `nox -s format`, `nox -s lint_flake8`, `nox -s lint_pylint`, `nox -s typecheck` or even `nox -s test`.

**Comment by rkaminsk** [comment]
precommit manages it's own virtual environments. I think that using nox here is not a good idea.

**Comment by rkaminsk** [comment]
Should we just drop the format session in favor of pre-commit?

**Comment by MaxOstrowski** [comment]
As pre-commit can be skipped I think that the formatting check should be part of the CI tests. So running `black`, `pylint`, `mypy`, etc... should be done when running the tests. Otherwise people will checkin and merge code that is not up to their standards and from thereon always skip the pre-commit.
