### ISSUE TITLE
Moving this project to potassco

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/python-project-template#21]
I think it makes sense to move this project to potassco, as this is the template for the projects there, right ? Also the documentation links and other stuff usually points to there.

**Comment by sthiele** [comment]
To increase discoverability, you could still pin the template in any other org.

**Comment by rkaminsk** [comment]
Ack. But let's get the latest PRs in first.

**Comment by rkaminsk** [comment]
Done.
