### ISSUE TITLE
logger.py and parser.py update

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/python-project-template#25]
I think these files could need an update, but maybe we can collect first which things need to be done.

- add type information, otherwise these files interfere with `mypy --strict`
- remove "levels" dict as logging has support for these strings directly
- I had a bit of a hassle to adopt the logging system in cases where I build a python library with this template
According to https://docs.python.org/3/howto/logging.html
i would revert to using `logger = logging.getLogger(__name__)` but we still might wanna have a initialization function

**Comment by rkaminsk** [comment]
I added type information. We don't really have to use `__name__` because the logger is created in `__main__`. Giving it the name `main` is just fine. When the setup logger method is used elsewhere, it could be called as you suggest.

**Comment by MaxOstrowski** [comment]
I agree for executable. My point was to be able to use the project-template for a library. Then several loggers in different libraries have to be coordinated and this seems to be the standard way to do it.
For our application class it does not really matter.

I'm not a fan of the `logger.py` as it adds a lot of things where

- i'm not sure what they are doing
- i'm not a fan of adding complexity to add color
- using the template for a library and setting sys.strerr as a streamhandler can be bad. The person using our library should decide on their own where the logging goes. As an example, in the ngo `__main__.py` i setup the logger to write to stderr. For the API use of `ngo` as a library, I don't want to do this, because then everybody using the API gets error messages to stderr and can't redirect them to their own logging system, etc...

@susuhahnml what do you think ?

**Comment by susuhahnml** [comment]
I agree that we need to set it up so that it works well as a library. Regarding the color, I really like having an output with colors, i think it improves a lot readability. Regarding the point of the standard error, I am not sure I fully follow. You mean that when you log a message it goes to the corresponding logger and not the stderr?

**Comment by rkaminsk** [comment]
@susuhahnml there  are many different targets one can log to. stderr is just one possibility. Depending on the type of project, stderr might not be a good target to log messages too.

@MaxOstrowski do we already have a project that can serve as a good role model? If yes, we can incorporate the logger setup from there. Otherwise, we can also just keep the current one and do this later. After all it's just a template and meant to be changed and extended anyway.

**Comment by MaxOstrowski** [comment]
Regardings the colors:
Colors can be nice as visual output, but I fear that dependent on the output target (text file, different consolve, html, database, etc...) that they might interfere with the target system and leave ugly unrecognized characters somewhere.

Regarding stderr:
It should not be the default if your project is used as a library. I think with your setup it is not possible to redirect your logger to something else and it might interfere with the users intended use of stderr.

I started with this template for [ngo](https://github.com/potassco/ngo) but simply removed any setup code because it was too simple.
In `main.py` I do call:
```
logging.basicConfig(stream=sys.stderr, level=args.log)
```
to setup my application to write logs to stderr. Furthermore, my application allows to set a logging level as an argument in the parser. Thats it, nothin more.
In my actual source files I use:
```
log = logging.getLogger(__name__)
```
at the beginning of each file, as I have several modules that I want to log separately, but this might be different for other projects and you might wanna go for something like:
```
log = logging.getLogger("fillname")
```
to have a common log for your whole application.


The advantage of this very slim setup is, that `logging.basicConfig(stream=sys.stderr, level=args.log)` does not get executed when you use `ngo` as a library. But logging still takes place.
You can easily setup the configuration in your own project that uses the `ngo` api e.g.
```
logging.basicConfig(stream="debuglog.txt", level="DEBUG")
```
and all logging goes to your log file, including the logging of `ngo`.
It all automatically applies to all your python libraries that use this proposed principle, and according to https://docs.python.org/3/howto/logging.html that is the way to use the logging system.

The filtering is already done by the `logging` lib, the formatting is the standard format `logging` proposes and I do not see a reason to change it for a general python-template.

**Comment by sthiele** [comment]
Shouldn't one use something like [`isatty()`](https://docs.python.org/3/library/io.html#io.IOBase.isatty) to detect if the output is a terminal.

**Comment by rkaminsk** [comment]
> Shouldn't one use something like [`isatty()`](https://docs.python.org/3/library/io.html#io.IOBase.isatty) to detect if the output is a terminal?

One can. :)

**Comment by rkaminsk** [comment]
I am done here. If there are further refinement proposals, just add a PR.
