### ISSUE TITLE
Change version of autoflake for pre-commit

### ISSUE THREAD

**Issue by nrueh** [potassco/python-project-template#40]
I got the following error when running the pre-commit. This seems to have to do with the fact that `distutils` got removed in Python 3.12.

```
autoflake................................................................Failed
- hook id: autoflake
- exit code: 1

Traceback (most recent call last):
  File "/Users/nicolasruhling/.cache/pre-commit/repos25c4xze/py_env-python3.12/bin/autoflake", line 5, in <module>
    from autoflake import main
  File "/Users/nicolasruhling/.cache/pre-commit/repos25c4xze/py_env-python3.12/lib/python3.12/site-packages/autoflake.py", line 32, in <module>
    import distutils.sysconfig
ModuleNotFoundError: No module named 'distutils'
```

Apparently, this dependency got fixed in a newer autoflake version (currently v1.4 is specified in the `.pre-commit-config.yaml` but the most recent is v2.3.0).

Is there any reason not to adapt to that version? 
The error disappeared for me with this change.

**Comment by rkaminsk** [comment]
Then let's just update the versions in pre-commit. Would you care to open a PR?

**Comment by rkaminsk** [comment]
Updating the other versions would also be nice. :wink:

**Comment by nrueh** [comment]
Nice! I did it by hand already but there seems to be an error with black in the tests
